name = "pastebin-worker"
account_id = "516d0a360ccdea88dd79e9cf5d2bc3aa"

[vars]
ENVIRONMENT = "production"
BASE_URL = "https://as.al"


# 如果不使用自定义域名，将下面的代码注释掉
[[routes]]
pattern = "as.al"
custom_domain = true

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = "pastes"

[[d1_databases]]
binding = "DB"
database_name = "pastebins"
database_id = "fecdd0c9-e87a-42d2-a6a7-983ee874f579"
migrations_dir = "./drizzle"
